### ISSUE TITLE
problems in building

### ISSUE THREAD

**Issue by BouchamaDjad** [Modern-Compilers-Lab/MLAutoScheduler#1]
when executing the command for building this repo
` cmake --build . `
the following error appears

![image](https://github.com/user-attachments/assets/c7acdc6e-4b65-4bd0-b4b9-245e56d1d538)

it seems that the file **mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h** is missing from llvm branch **release/17.x** 

on the other hand, the **main** branch is missing this file **mlir/include/mlir/Dialect/Transform/IR/TransformInterfaces.h** which also triggers another error if we build using main branch of llvm 

![image](https://github.com/user-attachments/assets/26f70286-ac49-42e7-95ed-c41740562c19)

**Comment by nassimiheb** [comment]
You should use the LLVM release 18, I updated the README file.
